<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>2c8bb286-9389-4bf0-aa3a-4d2bda28fc81</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Colors.Application\Colors.Application.csproj" />
    <ProjectReference Include="..\Colors.Infrastructure\Colors.Infrastructure.csproj" />
  </ItemGroup>

</Project>
