// <auto-generated />
using System;
using Colors.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Colors.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ColorsDbContext))]
    [Migration("20260805154536_AddThermoforming")]
    partial class AddThermoforming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("bag_barcode_seq");

            modelBuilder.HasSequence<int>("batch_number_seq");

            modelBuilder.HasSequence<int>("issue_ticket_number_seq");

            modelBuilder.HasSequence("pallet_barcode_seq");

            modelBuilder.HasSequence<int>("recipe_number_seq");

            modelBuilder.HasSequence("roll_barcode_seq");

            modelBuilder.Entity("Colors.Domain.Entities.Barcodes.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ux_barcodes_value");

                    b.HasIndex("ObjectType", "ObjectId")
                        .HasDatabaseName("ix_barcodes_object");

                    b.ToTable("Barcodes", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialInventory", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaterialId");

                    b.ToTable("MaterialInventory", null, t =>
                        {
                            t.HasCheckConstraint("ck_material_inventory_not_negative", "\"CurrentQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialInventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IssueTicketId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MovementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovementTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int?>("ShiftReportId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex("ShiftReportId");

                    b.HasIndex("UserId");

                    b.HasIndex("MaterialId", "MovementDate")
                        .HasDatabaseName("ix_material_movements_material_date");

                    b.ToTable("MaterialInventoryMovements", null, t =>
                        {
                            t.HasCheckConstraint("ck_material_movements_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialIssueTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IssuedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ShiftLineId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("IssuedByUserId");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_issue_tickets_number");

                    b.HasIndex("ShiftLineId", "Status")
                        .HasDatabaseName("ix_issue_tickets_line_status");

                    b.ToTable("MaterialIssueTickets", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialIssueTicketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IssuedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ReturnedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TicketId", "MaterialId")
                        .IsUnique()
                        .HasDatabaseName("ux_issue_lines_ticket_material");

                    b.ToTable("MaterialIssueTicketLines", null, t =>
                        {
                            t.HasCheckConstraint("ck_issue_lines_issued_positive", "\"IssuedQuantity\" > 0");

                            t.HasCheckConstraint("ck_issue_lines_returned_not_negative", "\"ReturnedQuantity\" >= 0");

                            t.HasCheckConstraint("ck_issue_lines_returned_within_issued", "\"ReturnedQuantity\" <= \"IssuedQuantity\"");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_colors_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_colors_name");

                    b.ToTable("Colors", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BarcodeTracked")
                        .HasColumnType("boolean");

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("UnitWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_materials_code");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.MaterialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IssuedOnTickets")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_material_categories_name");

                    b.ToTable("MaterialCategories", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.MaterialPackaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefaultReceiving")
                        .HasColumnType("boolean");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityInBaseUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("MaterialId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ux_material_packagings_material_unit");

                    b.ToTable("MaterialPackagings", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Mould", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_moulds_name");

                    b.ToTable("Moulds", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.MovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_movement_types_name");

                    b.ToTable("MovementTypes", null, t =>
                        {
                            t.HasCheckConstraint("ck_movement_types_direction", "\"Direction\" IN (1, -1)");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BagsPerPallet")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAbsorbent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MouldId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PiecesPerBag")
                        .HasColumnType("integer");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SmallBagsPerBag")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_products_name");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("MouldId", "IsAbsorbent")
                        .IsUnique()
                        .HasDatabaseName("ux_products_mould_absorbent");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_product_types_name");

                    b.ToTable("ProductTypes", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("FormsBags")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("MakesRolls")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RecordsMachineSettings")
                        .HasColumnType("boolean");

                    b.Property<bool>("TakesRawMaterial")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_production_lines_name");

                    b.ToTable("ProductionLines", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_shifts_name");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_units_name");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ShiftLineId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_batches_number");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ShiftLineId")
                        .HasDatabaseName("ix_batches_shift_line");

                    b.ToTable("Batches", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.ProducedBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PieceCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ThermoProductionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_produced_bags_status");

                    b.HasIndex("ThermoProductionId")
                        .HasDatabaseName("ix_produced_bags_production");

                    b.ToTable("ProducedBags", null, t =>
                        {
                            t.HasCheckConstraint("ck_produced_bags_positive", "\"Weight\" > 0 AND \"PieceCount\" > 0");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.Roll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("DailySerial")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("ProducedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProducedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date");

                    b.Property<int>("RecipeVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("RollCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProducedByUserId");

                    b.HasIndex("RecipeVersionId");

                    b.HasIndex("RollCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rolls_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rolls_status");

                    b.HasIndex("ProductionDate", "DailySerial")
                        .IsUnique()
                        .HasDatabaseName("ux_rolls_date_serial");

                    b.ToTable("Rolls", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.RollTestReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Length")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PlateWeight")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("RollId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TestedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThicknessLm")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("ThicknessLs")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("ThicknessRm")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("ThicknessRs")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.HasKey("Id");

                    b.HasIndex("RollId")
                        .IsUnique()
                        .HasDatabaseName("ux_roll_tests_roll");

                    b.HasIndex("TestedByUserId");

                    b.ToTable("RollTestReports", null, t =>
                        {
                            t.HasCheckConstraint("ck_roll_tests_positive", "\"Weight\" > 0 AND \"Length\" > 0 AND \"PlateWeight\" > 0");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.ThermoProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OperatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RollId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftLineId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("RollId")
                        .IsUnique()
                        .HasDatabaseName("ux_thermo_productions_roll");

                    b.HasIndex("ShiftLineId")
                        .HasDatabaseName("ix_thermo_productions_shift_line");

                    b.ToTable("ThermoProductions", null, t =>
                        {
                            t.HasCheckConstraint("ck_thermo_finished_after_started", "\"FinishedAt\" IS NULL OR \"FinishedAt\" >= \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.ThermoTestReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbsorbentPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("BagCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("BagWeight")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PieceCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("PieceWeight")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TestedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ThermoProductionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TestedByUserId");

                    b.HasIndex("ThermoProductionId")
                        .IsUnique()
                        .HasDatabaseName("ux_thermo_tests_production");

                    b.ToTable("ThermoTestReports", null, t =>
                        {
                            t.HasCheckConstraint("ck_thermo_tests_positive", "\"BagCount\" > 0 AND \"PieceCount\" > 0 AND \"PieceWeight\" > 0 AND \"BagWeight\" > 0 AND \"AbsorbentPercentage\" >= 0 AND \"AbsorbentPercentage\" <= 100");
                        });
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAbsorbent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("UsesRecycle")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_families_name");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("RecipeFamilies", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBaseResin")
                        .HasColumnType("boolean");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxPercentage")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("MinPercentage")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<int>("RecipeVersionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetPercentage")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RecipeVersionId", "MaterialId")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_ingredients_version_material");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RecipeFamilyId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RecipeFamilyId")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_versions_one_current_per_family")
                        .HasFilter("\"Status\" = 'Current'");

                    b.HasIndex("RecipeNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_versions_number");

                    b.HasIndex("RecipeFamilyId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_recipe_versions_family_version");

                    b.ToTable("RecipeVersions", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CycleTimeSeconds")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal?>("DowntimeHours")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<int?>("FeedDistanceMm")
                        .HasColumnType("integer");

                    b.Property<int?>("MachineSpeed")
                        .HasColumnType("integer");

                    b.Property<int?>("MouldId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("ProductionEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("ProductionStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ShiftReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MouldId");

                    b.HasIndex("ProductionLineId")
                        .HasDatabaseName("ix_shift_lines_line");

                    b.HasIndex("ShiftReportId", "ProductionLineId")
                        .IsUnique()
                        .HasDatabaseName("ux_shift_lines_report_line");

                    b.ToTable("ShiftLines", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ElectricityEndMeter")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("ElectricityStartMeter")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SupervisorUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SupervisorUserId");

                    b.HasIndex("ProductionDate", "ShiftId")
                        .IsUnique()
                        .HasDatabaseName("ux_shift_reports_date_shift");

                    b.ToTable("ShiftReports", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTrainee")
                        .HasColumnType("boolean");

                    b.Property<int>("ShiftLineId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ShiftLineId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_shift_workers_line_user");

                    b.ToTable("ShiftWorkers", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftWorkerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftWorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ShiftWorkerId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ux_shift_worker_roles_worker_role");

                    b.ToTable("ShiftWorkerRoles", (string)null);
                });

            modelBuilder.Entity("Colors.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Colors.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_users_employee_number");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Colors.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialInventory", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Material", "Material")
                        .WithOne()
                        .HasForeignKey("Colors.Domain.Entities.Inventory.MaterialInventory", "MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialInventoryMovement", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.MasterData.MovementType", "MovementType")
                        .WithMany()
                        .HasForeignKey("MovementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Shifts.ShiftReport", "ShiftReport")
                        .WithMany()
                        .HasForeignKey("ShiftReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MovementType");

                    b.Navigation("ShiftReport");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialIssueTicket", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Shifts.ShiftLine", "ShiftLine")
                        .WithMany()
                        .HasForeignKey("ShiftLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftLine");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialIssueTicketLine", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Inventory.MaterialIssueTicket", null)
                        .WithMany("Lines")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Material", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.MasterData.MaterialCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.MaterialPackaging", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Material", null)
                        .WithMany("Packagings")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.MasterData.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Product", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Mould", "Mould")
                        .WithMany()
                        .HasForeignKey("MouldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.MasterData.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mould");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.Batch", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Shifts.ShiftLine", "ShiftLine")
                        .WithMany()
                        .HasForeignKey("ShiftLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftLine");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.ProducedBag", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.MasterData.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Production.ThermoProduction", "ThermoProduction")
                        .WithMany("Bags")
                        .HasForeignKey("ThermoProductionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("ThermoProduction");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.Roll", b =>
                {
                    b.HasOne("Colors.Domain.Entities.Production.Batch", "Batch")
                        .WithMany("Rolls")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.MasterData.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ProducedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Recipes.RecipeVersion", "RecipeVersion")
                        .WithMany()
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Color");

                    b.Navigation("RecipeVersion");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.RollTestReport", b =>
                {
                    b.HasOne("Colors.Domain.Entities.Production.Roll", "Roll")
                        .WithOne("TestReport")
                        .HasForeignKey("Colors.Domain.Entities.Production.RollTestReport", "RollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roll");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.ThermoProduction", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Production.Roll", "Roll")
                        .WithOne()
                        .HasForeignKey("Colors.Domain.Entities.Production.ThermoProduction", "RollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Shifts.ShiftLine", "ShiftLine")
                        .WithMany()
                        .HasForeignKey("ShiftLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roll");

                    b.Navigation("ShiftLine");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.ThermoTestReport", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Production.ThermoProduction", "ThermoProduction")
                        .WithOne("TestReport")
                        .HasForeignKey("Colors.Domain.Entities.Production.ThermoTestReport", "ThermoProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ThermoProduction");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeFamily", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Recipes.RecipeVersion", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeVersion", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Recipes.RecipeFamily", "Family")
                        .WithMany("Versions")
                        .HasForeignKey("RecipeFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftLine", b =>
                {
                    b.HasOne("Colors.Domain.Entities.MasterData.Mould", "Mould")
                        .WithMany()
                        .HasForeignKey("MouldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Colors.Domain.Entities.MasterData.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Shifts.ShiftReport", "ShiftReport")
                        .WithMany("Lines")
                        .HasForeignKey("ShiftReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mould");

                    b.Navigation("ProductionLine");

                    b.Navigation("ShiftReport");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftReport", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.MasterData.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftWorker", b =>
                {
                    b.HasOne("Colors.Domain.Entities.Shifts.ShiftLine", null)
                        .WithMany("Workers")
                        .HasForeignKey("ShiftLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftWorkerRole", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Colors.Domain.Entities.Shifts.ShiftWorker", null)
                        .WithMany("Roles")
                        .HasForeignKey("ShiftWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Colors.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Colors.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Colors.Domain.Entities.Inventory.MaterialIssueTicket", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Colors.Domain.Entities.MasterData.Material", b =>
                {
                    b.Navigation("Packagings");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.Batch", b =>
                {
                    b.Navigation("Rolls");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.Roll", b =>
                {
                    b.Navigation("TestReport");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Production.ThermoProduction", b =>
                {
                    b.Navigation("Bags");

                    b.Navigation("TestReport");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeFamily", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Recipes.RecipeVersion", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftLine", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftReport", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Colors.Domain.Entities.Shifts.ShiftWorker", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
